# Generated by Django 6.1 on 2026-08-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
